Fixed AttributeError when using inline editing.
AttributeError: 'ATDocumentFieldsView' object has no attribute 'absolute_url'.
Inline editing then still does not work though (checked on Plone 4.2 dev).

Conflicts:

	CHANGES.txt
	Products/TinyMCE/utility.py